### ISSUE TITLE
tns run android --bundle errors with nativescript 3.4.0

### ISSUE THREAD

**Issue by skhye05** [EddyVerbruggen/nativescript-nfc#17]
Hi Eddy,

I would like to thank you for this plugin. it has been very helpful and mentions a couple of errors i have notice while running the command tns run android --bundle. 

When i run tns run android command these errors don't appear.

I have two page where I want to use the NFC plugin `home` and `test` pages and I am using `nfc.helper` class to use the plugin method.

## **The First Error**

This error comes up when I am importing the NFC helper class in both of my components pages

```
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:D:\Work\MOBILE\NATIVESCRIPT\NFCTest\platforms\android\app\src\main\java\com\tns\NativeScriptNfcActivity.java Class: com.tns.NativeScriptNfcActivity
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:68)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Work\MOBILE\NATIVESCRIPT\NFCTest\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 284

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_144\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
```
I later try to import the plugin in both components instead of using the helper and the error still come up.

It looks like I am unable to use (import) the plugin in multiple pages/component. Do you have a workaround this issues?

## **The Second Error**

After noticing the first error I tried to remove the class in one of the page/components and try to run the command again, this time around i am able to build the app but when it launches the following error come up:

`System.err: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.nativescript.NFCTest/com.tns.NativeScriptNfcActivity}: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptNfcActivity'`

## Here is the relevant files of the app:

**Home.component.ts**
```
import { Component, OnInit } from "@angular/core";
import { RouterExtensions } from "nativescript-angular";
import { NfcHelper } from "../helper/nfc.helper";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {

    nfcHelper: NfcHelper;

    constructor(private router: RouterExtensions) {
        this.nfcHelper = new NfcHelper();
    }

    ngOnInit(): void {
    }


    public goto() {
        this.router.navigate(['/test']);
    }
}

```

**Test.component.ts**
```
import { Component, OnInit } from "@angular/core";
import { NfcHelper } from "../helper/nfc.helper";


@Component({
    selector: "Test",
    moduleId: module.id,
    templateUrl: "./test.component.html"
})
export class TestComponent implements OnInit {

    nfcHelper: NfcHelper;

    constructor() {
        this.nfcHelper = new NfcHelper();
    }

    ngOnInit(): void {
    }

}

```

**nfc.helper.ts**
```
import { Nfc, NfcTagData, NfcNdefData } from "nativescript-nfc";

export class NfcHelper {
    private nfc: Nfc;

    constructor() {
        this.nfc = new Nfc();
    }

    public read() {
        this.nfc.available().then((avail) => {
            this.nfc.setOnTagDiscoveredListener((data: NfcTagData) => {
                console.log("Discovered a tag with ID " + data.id);

            }).then(() => {
                console.log("OnTagDiscovered listener added");
            });
        });

    }

    public remove() {
        this.nfc.setOnTagDiscoveredListener(null).then(() => {
            // Toast.makeText("OnNdefDiscovered listener removed").show();
            console.log("OnNdefDiscovered listener removed");
        })
    }

}
```

**Package.json**
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.NFCTest",
    "tns-android": {
      "version": "3.4.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "nativescript-angular": "^5.0.0",
    "nativescript-nfc": "2.1.2",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^3.4.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.0.0",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "0.5.1",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.4.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```

Can you please take a look and assist when possible.

Thanks

**Comment by EddyVerbruggen** [comment]
You may want to make that NFCHelper a singleton so it's only instantiated once. Just create an Angular service, provide it in the app module, and inject it in any component you need it.

That being said, I still wouldn't expect that error - is there a repo I can clone to see this myself?

**Comment by skhye05** [comment]
No I have no repo, but i can create one

**Comment by skhye05** [comment]
Hey @EddyVerbruggen,

You can find the project here : [project repo](https://github.com/skhye05/Nativescript-nfc-test.git)

**Comment by EddyVerbruggen** [comment]
Thx @skhye05! It's a simple matter of cloning, `npm i` and `tns run android` to reproduce it?

**Comment by skhye05** [comment]
Yes,
`npm i` and `tns run android --bundle`

**Comment by EddyVerbruggen** [comment]
I've been able to reproduce your issue. Hope to find a solution..

**Comment by EddyVerbruggen** [comment]
Tried a few things but it really looks like something is broken upstream. We may need to ask this in the https://github.com/NativeScript/android-runtime repo... found this issue just now: https://github.com/NativeScript/android-runtime/issues/911

**Comment by Plamen5kov** [comment]
Hi @skhye05, you can check out [this](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) to help you with the migration of your project.

**Comment by skhye05** [comment]
@Plamen5kov I have done the migration and the issue still occurs...

**Comment by Plamen5kov** [comment]
@skhye05 I'm sorry to hear you encounter issues with your project. I'd suggest opening a new issue, describing your problem in detail so we can do the best we can to help you to figure out the problem.

**Comment by des-esseintes** [comment]
I can confirm the issue, introduced webpack to my app w/ this great nfc plugin (thank you for your work, using bt, nfc and going to use fingerprint one as well) and getting that activity error: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptNfcActivity'
the app is pure js.

**Comment by EddyVerbruggen** [comment]
@des-esseintes Looks like something like https://github.com/NativeScript/nativescript-dev-webpack/issues/446 needs to be added to the readme. Can you perhaps give it a try?

**Comment by des-esseintes** [comment]
hello.
i feel very stupid, but can't get it working :)
at firsrt ie tried the ts version, like on the link you posted. as my project is js only i had to add ts support, but still could not get it buit -- always complains about missing 'android'.
ok so i copied the corresponding portion of the code from nfc.android.js from node_modules/nativescript-nfc and now it's giving me
```
Warning: there already is an extend called com.tns.NativeScriptNfcActivity.
Warning: The static binding generator will generate extend from:bundle.js implementation
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/home/k/dev/android/firedoor/platforms/android/app/src/main/java/com/tns/NativeScriptNfcActivity.java Class: com.tns.NativeScriptNfcActivity
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:68)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

```

i'm probably doing something wrong here as am not a 'pro' {N} developer and dont fully understand its internals.

**Comment by EddyVerbruggen** [comment]
Don't feel stupid, this is actually a very hard problem.

I'm going to see if it's easier to fix with NativeScript 4 (hoping to get rid of this file entirely).

You were right to copy the .js file and use that, and change webpack.config.js to add it as a 'MainAcivity' as mentioned in the linked issues.

Perhaps try removing the platforms/android folder and build again?

**Comment by des-esseintes** [comment]
yesterday i've totally messed the whole project with all those rebuild (a weird {N} bugs started to appear), i think i'll try again, from scratch, later.
i think i'll stick with some tiny test app first and then port the changes to my main one. i'll report back as soon as i get some results. thanks for your help

**Comment by des-esseintes** [comment]
Hello
I've created a test empty app, tried building in default mode with nfc activity -- ok
then tried to build w/ webpack -- failure
added portion of code from your android file (generated js version) -- working!
haven't ported it into my main app yet, though, but this is another question.

**Comment by skhye05** [comment]
Hi,

I have a found a workaround by importing the nfc class in app.component.ts and create a service with an eventEmitter to  emit the callback response after i get the reading data.

Here is the code:

#### app.component.ts

```TypeScript
import { Component } from "@angular/core";
import { Nfc } from "nativescript-nfc";
import { BroadcastService } from "./broadcast.service";
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public nfc = new Nfc();
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.nfc.available().then((avail) => {
            this.nfc.setOnTagDiscoveredListener((data: any) => {
                console.log("Discovered a tag with ID " + data.id);
                this.br.emit("MOI");

            }).then(() => {
                console.log("OnTagDiscovered listener added");
            });
        });
    }

    test() {
        console.log('from app component');
    }
}

```

**Comment by skhye05** [comment]
Hi,

I have a found a workaround by importing the nfc class in app.component.ts and create a service with an eventEmitter to  emit the callback response after i get the reading data.

Here is the code:

#### app.module.ts

```TypeScript
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { BroadcastService } from "./broadcast.service";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers:[
        BroadcastService
    ]
})
export class AppModule { }
```
#### app.component.ts

```TypeScript
import { Component } from "@angular/core";
import { Nfc } from "nativescript-nfc";
import { BroadcastService } from "./broadcast.service";
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public nfc = new Nfc();
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.nfc.available().then((avail) => {
            this.nfc.setOnTagDiscoveredListener((data: any) => {
                console.log("Discovered a tag with ID " + data.id);
                this.br.emit("MOI");

            }).then(() => {
                console.log("OnTagDiscovered listener added");
            });
        });
    }

    test() {
        console.log('from app component');
    }
}

```
#### home.component.ts

```TypeScript
```

#### test.component.ts

```TypeScript

**Comment by skhye05** [comment]
Hi,

I have a found a workaround by importing the nfc class in app.component.ts and create a service with an eventEmitter to  emit the callback response after i get the reading data.

Here is the code:

#### app.module.ts

```TypeScript
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { BroadcastService } from "./broadcast.service";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers:[
        BroadcastService
    ]
})
export class AppModule { }
```
#### app.component.ts

```TypeScript
import { Component } from "@angular/core";
import { Nfc } from "nativescript-nfc";
import { BroadcastService } from "./broadcast.service";
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public nfc = new Nfc();
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.nfc.available().then((avail) => {
            this.nfc.setOnTagDiscoveredListener((data: any) => {
                console.log("Discovered a tag with ID " + data.id);
                this.br.emit("MOI");

            }).then(() => {
                console.log("OnTagDiscovered listener added");
            });
        });
    }

    test() {
        console.log('from app component');
    }
}

```
#### home.component.ts

```TypeScript
import { Component, OnInit } from "@angular/core";
import { BroadcastService } from "../broadcast.service";
import { RouterExtensions } from "nativescript-angular/router";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    private sub: any;
    constructor(private br: BroadcastService, private router: RouterExtensions) {
    }

    ngOnInit(): void {
        this.sub = this.br.answer.subscribe((args) => {
            console.log('HOME ' + args);
            this.sub.unsubscribe();
        });
    }

    public goto() {
        this.router.navigate(['/test']);
    }
}

```

#### test.component.ts

```TypeScript
import { Component, OnInit } from "@angular/core";
import { BroadcastService } from "../broadcast.service";

@Component({
    selector: "Test",
    moduleId: module.id,
    templateUrl: "./test.component.html"
})
export class TestComponent implements OnInit {
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.br.answer.subscribe((args) => {
            console.log('TEST ' + args);
        });
    }
}

```

**Comment by skhye05** [comment]
Hi,

I have a found a workaround by importing the nfc class in app.component.ts and create a service with an eventEmitter to  emit the callback response after i get the reading data.

Here is the code:

#### app.module.ts

```TypeScript
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { BroadcastService } from "./broadcast.service";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers:[
        BroadcastService
    ]
})
export class AppModule { }
```
#### app.component.ts

```TypeScript
import { Component } from "@angular/core";
import { Nfc } from "nativescript-nfc";
import { BroadcastService } from "./broadcast.service";
@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public nfc = new Nfc();
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.nfc.available().then((avail) => {
            this.nfc.setOnTagDiscoveredListener((data: any) => {
                console.log("Discovered a tag with ID " + data.id);
                this.br.emit("MOI");

            }).then(() => {
                console.log("OnTagDiscovered listener added");
            });
        });
    }

    test() {
        console.log('from app component');
    }
}

```
#### broadcast.service.ts

```TypeScript
import { Injectable, EventEmitter } from "@angular/core";
import { Observable } from "tns-core-modules/ui/page/page";

@Injectable()
export class BroadcastService {
    public answer: EventEmitter<string>;
    constructor() {
        this.answer = new EventEmitter<string>();
    }

    emit(args): void {
        this.answer.emit(args);
    }
}

```
#### home.component.ts

```TypeScript
import { Component, OnInit } from "@angular/core";
import { BroadcastService } from "../broadcast.service";
import { RouterExtensions } from "nativescript-angular/router";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    private sub: any;
    constructor(private br: BroadcastService, private router: RouterExtensions) {
    }

    ngOnInit(): void {
        this.sub = this.br.answer.subscribe((args) => {
            console.log('HOME ' + args);
            this.sub.unsubscribe();
        });
    }

    public goto() {
        this.router.navigate(['/test']);
    }
}

```

#### test.component.ts

```TypeScript
import { Component, OnInit } from "@angular/core";
import { BroadcastService } from "../broadcast.service";

@Component({
    selector: "Test",
    moduleId: module.id,
    templateUrl: "./test.component.html"
})
export class TestComponent implements OnInit {
    constructor(private br: BroadcastService) {
    }

    ngOnInit(): void {
        this.br.answer.subscribe((args) => {
            console.log('TEST ' + args);
        });
    }
}

```

This work for me at the current moment and i hope it will help you as well @des-esseintes 
if you want me to create a repo with my code sample just let me know.

**Comment by ikhsan017** [comment]
is this issue still present in nativescript 4.0?

**Comment by EddyVerbruggen** [comment]
Should be OK now. See the webpack note in the readme.
